#ifndef EMBEDDED_UI_VERSION_H
#define EMBEDDED_UI_VERSION_H


#define EMBEDDED_UI_VERSION_MAJOR 0
#define EMBEDDED_UI_VERSION_MINOR 1
#define EMBEDDED_UI_VERSION_PATCH 0


#define EMBEDDED_UI_VERSION "0.1.0"


#endif